<script setup lang="ts">
import type { JokeRes } from "@/types";
import { useQuery } from "@tanstack/vue-query";

const jokeQuery = useQuery<JokeRes>({
  queryKey: ["AllJoke"],
  queryFn: () =>
    fetch(
      "https://v2.jokeapi.dev/joke/Miscellaneous,Pun,Spooky,Christmas?blacklistFlags=nsfw,religious,political,racist,sexist,explicit",
    ).then((res) => res.json()),
});
</script>

<template>
  <div class="max-w-md">
    <div v-if="jokeQuery.data.value && !jokeQuery.data.value?.error">
      <span class="text-left" v-if="jokeQuery.data.value.type == 'single'">
        {{ jokeQuery.data.value.joke }}
      </span>
      <div v-else class="grid gap-2">
        <span class="text-left">
          {{ jokeQuery.data.value.setup }}
        </span>
        <span class="text-left">
          {{ jokeQuery.data.value.delivery }}
        </span>
      </div>
    </div>
    <div v-else class="flex flex-col justify-center items-center mt-5">
      <IconCSS name="arcticons:bad-piggies" size="150" />
      <span class="text-2xl">No Joke found</span>
      <span> (A a piggy stole them!) </span>
    </div>

    <button class="btn btn-block mt-5" @click="jokeQuery.refetch()">
      New Joke
    </button>
    <p class="text-xs">
      All jokes are generated by
      <a href="https://jokeapi.dev" class="link">The Joke API</a> and DO NOT
      reflect the opinons or values of the creator of this website.
    </p>
  </div>
</template>
